import Container from "@/components/ui/container";
import "./globals.css";
import { plusJakartaSans } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(plusJakartaSans.variable, "antialiased font-sans")}>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
